{
  'report_type': 'dynamics_by_spots', # тип отчета
  'data_lang': 'ru', # задаем язык выгрузки
  'multiple_files': True, # True, если разбиваем выгрузки по месяцам/неделям
  'period': {
    'date_filter': Null, #['2023-09-01', '2023-09-02'], #Null, # Задаем явно период ['2023-09-01', '2023-09-31'] или Null
    'last_time': { #если нужно последние несколько мес #
      'period_type': 'm',
      'period_num': '11',
      'include_current': True
    }
  },
  'category_name': 'Парфюмерия',
  'ad_filter': 'articleLevel4Id in (4767, 4911)  and adIssueStatusId = R', # Парфюмерия
    #'articleLevel2Id = 2272 and adIssueStatusId = R' Финансовые услуги
  'basedemo_filter': 'sex = 2 AND age >= 25 AND age <= 45'   # задаем ЦА w 25-45 BC
    #'age >= 30 AND age <= 60 AND incomeGroupRussia IN (2,3)',   #all 30-60 BC


 }