[
  {
    'report_subtype': 'DYNAMICS_BY_SPOTS', # тип отчета
    'data_lang': 'ru', # задаем язык выгрузки
    'folder':'raw_data',
    'multiple_files': True, # True, если разбиваем выгрузки по месяцам/неделям
    'category_name': 'Парфюмерия',
    'ad_filter': 'articleLevel4Id = 4973  and adIssueStatusId = R',  #Парфюмерия
    #'articleLevel4Id in (4767, 4911)  and adIssueStatusId = R',  Парфюмерия
    #'articleLevel2Id = 2272 and adIssueStatusId = R' Финансовые услуги
    'target_audiences': {
      'all 30-60 BC': 'age >= 30 AND age <= 60 AND incomeGroupRussia IN (2,3)',
      'w 25-45 BC': 'sex = 2 AND age >= 25 AND age <= 45'
    },
    'period': {
      'date_filter': Null, #['2023-09-01', '2023-09-02'], #Null, # Задаем явно период ['2023-09-01', '2023-09-31'] или Null
      'last_time': { #если нужно последние несколько мес #
        'period_type': 'm',
        'period_num': '11',
        'include_current': True
      }
    },
  },
  {
    'report_subtype': 'DYNAMICS_BY_SPOTS_DICT', # тип отчета
    'data_lang': 'ru', # задаем язык выгрузки
    'folder':'dict',
    'multiple_files': False, # True, если разбиваем выгрузки по месяцам/неделям
    'category_name': 'Парфюмерия',
    'ad_filter': 'articleLevel4Id = 4973  and adIssueStatusId = R',  #Парфюмерия
    #'articleLevel4Id in (4767, 4911)  and adIssueStatusId = R',  Парфюмерия
    #'articleLevel2Id = 2272 and adIssueStatusId = R' Финансовые услуги
    'target_audiences': { Null: Null },
    'period': {
      'date_filter': Null, #['2023-09-01', '2023-09-02'], #Null, # Задаем явно период ['2023-09-01', '2023-09-31'] или Null
      'last_time': { #если нужно последние несколько мес #
        'period_type': 'm',
        'period_num': '11',
        'include_current': True
      }
    }
  }
#  {

#  }
 ]