[
  {
    'report_subtype': 'DYNAMICS_BY_SPOTS', # тип отчета
    'data_lang': 'en', # задаем язык выгрузки
    'folder':'raw_data',
    'multiple_files': True, # True, если период больше 1 года, разбиваем выгрузки по месяцам/неделям
    'category_name': 'легковые автомобили',
    'ad_filter': 'articleLevel3Id = 123 and adIssueStatusId = R', #ЛЕГКОВОЙ АВТОТРАНСПОРТ

    'target_audiences': {
      'all 25-44 BC': 'age >= 25 AND age <= 44 AND incomeGroupRussia IN (2,3)',
      'all 25-54 BC': 'age >= 25 AND age <= 54 AND incomeGroupRussia IN (2,3)',
      'm 25-44 BC': 'sex = 1 AND age >= 25 AND age <= 44 AND incomeGroupRussia IN (2,3)',
      'm 25-54 BC': 'sex = 1 AND age >= 25 AND age <= 54 AND incomeGroupRussia IN (2,3)'
    },
    'period': {
      'date_filter': ['2023-01-01', '2024-01-07'], #['2023-09-01', '2023-09-02'], #Null, # Задаем явно период ['2023-09-01', '2023-09-31'] или Null
      'last_time': { #если нужно последние несколько мес #
        'period_type': 'm',
        'period_num': '4',
        'include_current': True
      }
    },
  },
  {
    'report_subtype': 'DYNAMICS_BY_SPOTS_DICT', # тип отчета
    'data_lang': 'en', # задаем язык выгрузки
    'folder':'dict',
    'multiple_files': True, # True, если период больше 1 года, разбиваем выгрузки по месяцам/неделям
    'category_name': 'легковые автомобили',
    'ad_filter': 'articleLevel3Id = 123 and adIssueStatusId = R', #ЛЕГКОВОЙ АВТОТРАНСПОРТ
    'target_audiences': { Null: Null },
    'period': {
      'date_filter': ['2023-01-01', '2024-01-07'], #['2023-09-01', '2023-09-02'], #Null, # Задаем явно период ['2023-09-01', '2023-09-31'] или Null
      'last_time': { #если нужно последние несколько мес #
        'period_type': 'y',
        'period_num': '4',
        'include_current': True
      }
    }
  }
#  {

#  }
 ]